services:

    Micro\BaseComponent\EventListener\ApiVersionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request}

    Micro\BaseComponent\EventListener\JsonListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request}

    Micro\BaseComponent\EventListener\ExceptionListener:
        arguments:
          - '@kernel'
          - '@logger'
        tags:
            - { name: kernel.event_listener, event: kernel.exception}

    Micro\BaseComponent\EventListener\ApiResponseListener:
        tags:
            - { name: kernel.event_listener, event: kernel.view}